### ISSUE TITLE
Not a big problem but...

### ISSUE THREAD

**Issue by anna-pokhilenko** [anna-pokhilenko/registration-form#1]
@muxlowc

Hello) I hope you are doing well during the whole quarantine thing! 
I already submitted the form with Markbot but I wanted to know how to make adjustments on these strokes. One is just a border, and another is a legend for the fieldset. 

<img width="759" alt="Screen Shot 2020-03-18 at 2 18 52 PM" src="https://user-images.githubusercontent.com/55008926/76994321-94898100-6924-11ea-88e3-f2f4acee3b71.png">
I was trying to inspect it but it didn't work.

**Comment by muxlowc** [comment]
@anna-pokhilenko  
1) try moving your H1 and P down into your form (just above your fieldset)

2) And try adding the gutter class to your form / remove your gutter class from everything else

Hope that helps!
